text = "El arrabio nacional debe colocarse lo más cerca posible del fondo de la cesta en la primera carga"
print(len(text))
print(text[0])
print(text[1])
print(text[-1])
print(text[-2])
print(text[:])
print(text[0:10])
print(text[10:20])
print(text[:20])
print(text[20:])
print(text[20:-5])
print(text[::2])
print(text[10:20:2])
